Task completed GP-118: Pooling
LighteatersStudio/TopDownShooter pull request #104
Opened 2023-09-20 15:29 UTC by Kjusok

https://lighteatersstudio.atlassian.net/jira/software/projects/GP/boards/1?selectedIssue=GP-118

Implemented a pool for destroyed projectiles

2023-09-21 17:42 UTC, ega-ega requested changes

2023-09-21 17:42 UTC, ega-ega commented on Assets/Scripts/Gameplay/Projectiles/ProjectilePool.cs
> +        public void AddProjectile(FlyInfo flyInfo, AttackInfo attackInfo)
Rename to "Spawn"

2023-09-21 17:42 UTC, ega-ega commented on Assets/Scripts/Gameplay/Projectiles/ProjectilePool.cs
> +                projectile = _projectiles[0];
?

2023-09-21 17:42 UTC, ega-ega commented on Assets/Scripts/Gameplay/Projectiles/ProjectilePool.cs
> +    public class ProjectilePool : MonoBehaviour
Why need Monobehaviour?

2023-09-22 19:33 UTC, Kjusok commented on Assets/Scripts/Gameplay/Projectiles/ProjectilePool.cs
> +    public class ProjectilePool : MonoBehaviour
Done

2023-09-22 19:33 UTC, Kjusok commented on Assets/Scripts/Gameplay/Projectiles/ProjectilePool.cs
> +        public void AddProjectile(FlyInfo flyInfo, AttackInfo attackInfo)
Removed

2023-09-23 07:14 UTC, ega-ega approved these changes

2023-09-23 07:14 UTC, merged