WIP Moving to level 3
LighteatersStudio/TopDownShooter pull request #107
Opened 2023-11-04 17:58 UTC by Kjusok

2023-11-22 19:06 UTC, ega-ega requested changes

2023-11-22 19:06 UTC, ega-ega commented on Assets/Scripts/Gameplay/Enemy/Spawners/EnemySpawner.cs
> +using Gameplay.AI;
pls remove unused namespace

2023-12-03 15:07 UTC, Kjusok commented on Assets/Scripts/Gameplay/Enemy/Spawners/EnemySpawner.cs
> +using Gameplay.AI;
Done

2023-12-04 17:46 UTC, ega-ega requested changes

2023-12-04 17:46 UTC, ega-ega commented on Assets/Scripts/Gameplay.Services/FX/PlayingFX.cs
> +        private Vector3 _direction;
Используй FXContext поле

2023-12-04 17:46 UTC, ega-ega commented on Assets/Scripts/Gameplay/Character/View/CharacterModelRoots.cs
> +        [SerializeField] private Transform _rightHand;
переименуй в Weapon

2023-12-04 17:46 UTC, ega-ega commented on Assets/Scripts/Gameplay/Projectiles/Projectile.cs
>              var target = other.GetComponent<IDamageable>();
перенеси и поставь перед IF

2023-12-04 17:46 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/Implementation/Weapon.cs
> +        private Transform _muzzleRoot;
замени на поле типа WeaponModelRoots

2023-12-04 17:46 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/Implementation/WeaponModelRoots.cs
> +        [SerializeField] private Transform _muzzle;
[field: SerializeFiled] public Transform Muzzle { get; }

2023-12-04 18:03 UTC, Kjusok commented on Assets/Scripts/Gameplay.Services/FX/PlayingFX.cs
> +        private Vector3 _direction;
Done

2023-12-04 18:04 UTC, Kjusok commented on Assets/Scripts/Gameplay/Character/View/CharacterModelRoots.cs
> +        [SerializeField] private Transform _rightHand;
Done

2023-12-04 18:21 UTC, Kjusok commented on Assets/Scripts/Gameplay/Projectiles/Projectile.cs
>              var target = other.GetComponent<IDamageable>();
Done

2023-12-04 18:25 UTC, Kjusok commented on Assets/Scripts/Gameplay/Weapons/Implementation/Weapon.cs
> +        private Transform _muzzleRoot;
Done

2023-12-04 18:52 UTC, Kjusok commented on Assets/Scripts/Gameplay/Weapons/Implementation/WeaponModelRoots.cs
> +        [SerializeField] private Transform _muzzle;
Нужен уточняющий вопрос

2023-12-05 18:18 UTC, ega-ega approved these changes

2023-12-05 18:18 UTC, merged