Added: Character selection window. System of modules for data processing
LighteatersStudio/TopDownShooter pull request #111
Opened 2024-02-18 08:49 UTC by Kjusok

2024-02-18 10:51 UTC, EgorShaldovRB requested changes

2024-02-18 10:51 UTC, EgorShaldovRB commented on ProjectSettings/TagManager.asset
> +  - AI
ужади тег пожадлуйста

2024-02-18 10:51 UTC, EgorShaldovRB commented on ProjectSettings/TagManager.asset
> +  - FirstCharacter
Перенеси вниз

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Sprites/Dark UI/DarkUI.unity
Удали сцены

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +        public event Action<bool> OnToggle;
Переименуй в галгол прошедшего времени без On

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +            if (_otherCharacterView != null && _otherCharacterView.IsToggled)
_otherCharacterView == true. сравнивай с bool

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +        [field: SerializeField] public bool IsToggled { get; protected set; }
Сделай сеттер приватом

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +    public class CharacterView : MonoBehaviour
Переложи в свою папку

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionScreen.cs
> +            _toBattleButton.onClick.AddListener(ActivateHighMode);
выполни RemoveListener

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionScreen.cs
> +        private bool _isFirstOn;
используй один int с индексом персонажа

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionScreen.cs
> +            _toBattleButton.gameObject.SetActive(_isFirstOn != _isSecondOn);
стартовое состояние индекса персонажа = -1

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +        [SerializeField] private CharacterView _otherCharacterView;
вылючением "другого" должен заниматься screen

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +
нужен метод:
**public void SetToggle(bool value, bool isSilence = false) {}**

isSilence == true означает не выкидывать ивент

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +    public class CharacterView : MonoBehaviour
вместе с SCREEN

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Meta/TopDownShooter.Meta.asmdef
> +        "GUID:e617c73ffc48cdf448de8ec39f4534bf"
Удали!

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/DataConfig.cs
> +        [field: SerializeField] public  AllPlayersData  AllPlayersData { get; protected set; }
сделай setter приватным

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/DataConfig.cs
> +    public class DataConfig: ScriptableObject
Удали это файл

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/AllPlayersData.cs
> +    public class AllPlayersData: ScriptableObject
переименуй PlayerCharactersSettings

 сделай IPlayerCharactersSettings с нужным контрактом

PlayerCharactersSettings имплиметриуй интерфейс

и в инсталлере забайнди именно интерфейс

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/AllPlayersData.cs
> +        [field: SerializeField] public PlayerSettings[] PlayerSettingsArray { get; protected set; }
сделай сеттер приватом

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +        private PlayerSettings _playerSettings;
сохраняй индекс

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +            _playerSettings = _dataConfig.AllPlayersData.PlayerSettingsArray[index];
Сделай проверку на выход за рамки массива и кинь ерор если за рамками

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +    public class SelectCharacterModule
Переименуй в SelectCharacterService

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +        public PlayerSettings GetPlayerSettings()
Передлай на проперти геттер

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +            _playerSettings = _dataConfig.AllPlayersData.PlayerSettingsArray[index];
Добавь евент

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +        public void GetPlayerCharacteristics()
удали не нуждные методы

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Collectables/RotateCollectables.cs
> +        [SerializeField] private float _duration = 2f;
добавь в конец "S"

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Materials/RenderTexture/CFBRenderTexture.renderTexture
Удали лишнее

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Prefabs/Gameplay/Player/PlayersConfig/FirstPlayerSettings.asset
Переименый в FirstPlayerCharcterSettings пожалуйста

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Prefabs/Gameplay/Player/PlayersConfig/SecondPlayerSettings.asset
Переименый в SecondPlayerCharcterSettings пожалуйста

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Prefabs/Gameplay/Player/PlayersConfig/PlayerSettings.asset
Удавли ненужный

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Prefabs/Gameplay/Player/PlayersConfig.meta
Переименуй в PlayerCharactersSettings

2024-02-18 10:51 UTC, EgorShaldovRB commented on Assets/Resources/DataConfig.asset
удали пожалдуйста

2024-02-18 11:17 UTC, Kjusok commented on ProjectSettings/TagManager.asset
> +  - AI
Done

2024-02-18 11:18 UTC, Kjusok commented on ProjectSettings/TagManager.asset
> +  - FirstCharacter
Done

2024-02-18 11:19 UTC, Kjusok commented on Assets/Sprites/Dark UI/DarkUI.unity
Done

2024-02-18 11:20 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +        public event Action<bool> OnToggle;
Done

2024-02-18 11:20 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +            if (_otherCharacterView != null && _otherCharacterView.IsToggled)
Done

2024-02-18 11:22 UTC, Kjusok commented on Assets/Prefabs/Gameplay/Player/PlayersConfig/FirstPlayerSettings.asset
Done

2024-02-18 11:22 UTC, Kjusok commented on Assets/Prefabs/Gameplay/Player/PlayersConfig/SecondPlayerSettings.asset
done

2024-02-18 11:22 UTC, Kjusok commented on Assets/Prefabs/Gameplay/Player/PlayersConfig/PlayerSettings.asset
done

2024-02-18 11:23 UTC, Kjusok commented on Assets/Prefabs/Gameplay/Player/PlayersConfig.meta
Done

2024-02-18 11:24 UTC, Kjusok commented on Assets/Resources/DataConfig.asset
Done

2024-02-18 11:25 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +        [field: SerializeField] public bool IsToggled { get; protected set; }
Done

2024-02-18 11:30 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +    public class CharacterView : MonoBehaviour
Done

2024-02-18 11:30 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionScreen.cs
> +            _toBattleButton.onClick.AddListener(ActivateHighMode);
Done

2024-02-18 11:52 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionScreen.cs
> +        private bool _isFirstOn;
Done

2024-02-18 11:53 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionScreen.cs
> +            _toBattleButton.gameObject.SetActive(_isFirstOn != _isSecondOn);
Сделал по другому

2024-02-18 13:20 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/MainMenu/CharacterView.cs
> +
Done

2024-02-18 13:20 UTC, Kjusok commented on Assets/Scripts/Meta/TopDownShooter.Meta.asmdef
> +        "GUID:e617c73ffc48cdf448de8ec39f4534bf"
Done

2024-02-18 13:21 UTC, Kjusok commented on Assets/Scripts/Gameplay/DataConfig.cs
> +        [field: SerializeField] public  AllPlayersData  AllPlayersData { get; protected set; }
Done

2024-02-18 13:21 UTC, Kjusok commented on Assets/Scripts/Gameplay/DataConfig.cs
> +    public class DataConfig: ScriptableObject
Done

2024-02-18 14:27 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/AllPlayersData.cs
> +    public class AllPlayersData: ScriptableObject
Done

2024-02-18 14:27 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/AllPlayersData.cs
> +        [field: SerializeField] public PlayerSettings[] PlayerSettingsArray { get; protected set; }
done

2024-02-18 14:29 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +        private PlayerSettings _playerSettings;
Done

2024-02-18 14:35 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +            _playerSettings = _dataConfig.AllPlayersData.PlayerSettingsArray[index];
Done

2024-02-18 14:36 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +    public class SelectCharacterModule
Done

2024-02-18 14:36 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +        public void GetPlayerCharacteristics()
Done

2024-02-18 14:37 UTC, Kjusok commented on Assets/Scripts/Gameplay/Collectables/RotateCollectables.cs
> +        [SerializeField] private float _duration = 2f;
done

2024-02-18 14:40 UTC, Kjusok commented on Assets/Materials/RenderTexture/CFBRenderTexture.renderTexture
Done

2024-02-18 14:43 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterModule.cs
> +        public PlayerSettings GetPlayerSettings()
Done

2024-02-21 13:18 UTC, ega-ega approved these changes

2024-02-21 13:18 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/IPlayerCharactersSettings.cs
> +        PlayerSettings[] PlayerSettingsArray { get; }
Измени возвращающиеся значение на 
IEnumerable<PlayerSettings>

2024-02-21 13:18 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterService.cs
> +                if (_index < 0 || _index >= _playerCharactersSettings.PlayerSettingsArray.Length)
перенеси проверку в метод установки индекса.

2024-02-21 13:18 UTC, ega-ega commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterView.cs
> +            _button.onClick.AddListener(() => SetToggle());
добавь отписку от этого события в OnDispose

2024-02-21 13:21 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/IPlayerCharactersSettings.cs
> +        PlayerSettings[] PlayerSettingsArray { get; }
IEnumerable<PlayerSettings>

2024-02-21 13:22 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/IPlayerCharactersSettings.cs
> +        PlayerSettings[] PlayerSettingsArray { get; }
PlayerSettings\<PlayerSettings \>

2024-02-21 13:22 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/IPlayerCharactersSettings.cs
> +        PlayerSettings[] PlayerSettingsArray { get; }
IEnumarable\<PlayerSettings\>

2024-02-21 18:10 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/IPlayerCharactersSettings.cs
> +        PlayerSettings[] PlayerSettingsArray { get; }
Done

2024-02-21 18:15 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterService.cs
> +                if (_index < 0 || _index >= _playerCharactersSettings.PlayerSettingsArray.Length)
Done

2024-02-21 18:30 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterView.cs
> +            _button.onClick.AddListener(() => SetToggle());
Done

2024-02-21 18:32 UTC, merged