Feature/adding character stats window
LighteatersStudio/TopDownShooter pull request #113
Opened 2024-02-24 15:20 UTC by Kjusok

2024-02-27 18:39 UTC, ega-ega requested changes

2024-02-27 18:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterService.cs
> +        public StatsInfo GetCharacterStats() =>
Удали проперти

2024-02-27 18:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterService.cs
> +        public IWeaponSettings GetStartWeaponStats() =>
Удали проперти

2024-02-27 18:39 UTC, ega-ega commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterSelectionScreen.cs
> +            _characterStatsView.Setup(_selectedCharacters.Count > 0);
давай сетапить пдеер сеттингс   Setup(SelectCharacterService.PlayerSetttings)

2024-02-27 18:39 UTC, ega-ega commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterSelectionScreen.cs
> +            _characterStatsView.Setup(_selectedCharacters.Count > 0);
не будем делать инъекцию сервиса в _characterStatsView

2024-02-27 18:39 UTC, ega-ega commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterStatsView.cs
> +            _healthText,
на каждое поле собсвеный аксесор

2024-02-27 18:39 UTC, ega-ega commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterView.cs
> +        private static readonly int Battlecry = Animator.StringToHash("Battlecry");
убери  static

2024-02-28 17:32 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterService.cs
> +        public StatsInfo GetCharacterStats() =>
Done

2024-02-28 17:32 UTC, Kjusok commented on Assets/Scripts/Gameplay/Player/Setttings/SelectCharacterService.cs
> +        public IWeaponSettings GetStartWeaponStats() =>
Done

2024-02-28 17:39 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterSelectionScreen.cs
> +            _characterStatsView.Setup(_selectedCharacters.Count > 0);
Done

2024-02-28 17:40 UTC, Kjusok commented on Assets/Scripts/UI/Views/Popups/CharacterSelectionMenu/CharacterStatsView.cs
> +            _healthText,
Done

2024-02-29 07:48 UTC, ega-ega approved these changes

2024-03-01 13:07 UTC, merged