Feature/shooting death and damage animations
LighteatersStudio/TopDownShooter pull request #116
Opened 2024-03-17 13:17 UTC by Kjusok

2024-03-20 18:28 UTC, LighteatersStudio requested changes

2024-03-20 18:28 UTC, LighteatersStudio commented on Assets/Scripts/Gameplay/Projectiles/Projectile.cs
> +        private bool IsFriend(IFriendOrFoeTag friendOrFoeTag)
Избыточные функции

2024-03-20 18:28 UTC, LighteatersStudio commented on Assets/Scripts/Gameplay/Character/View/CharacterAnimator.cs
> +            foreach (var material in _view.GetComponent<SkinnedMeshRenderer>().materials)
Спрятать работу с материалами в отедельный клас( Принцип единой отвественности)

2024-04-02 19:09 UTC, Kjusok commented on Assets/Scripts/Gameplay/Projectiles/Projectile.cs
> +        private bool IsFriend(IFriendOrFoeTag friendOrFoeTag)
done

2024-04-02 19:09 UTC, Kjusok commented on Assets/Scripts/Gameplay/Character/View/CharacterAnimator.cs
> +            foreach (var material in _view.GetComponent<SkinnedMeshRenderer>().materials)
done

2024-04-19 17:57 UTC, ega-ega approved these changes

2024-04-19 17:58 UTC, LighteatersStudio approved these changes

2024-04-19 18:23 UTC, merged