[WIP] Cutscene
LighteatersStudio/TopDownShooter pull request #142
Opened 2024-10-10 11:19 UTC by chexpk

[Task](https://app.asana.com/0/1208366970413384/1208366970413406/f)

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Cutscene/Cutscene.cs
> +        private void Construct(ICinemachineBrainProvider сinemachineBrainProvider)
public

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Scenario/FirstCutsceneScenario/FirstCutsceneScenario.cs
> +    public class FirstCutsceneScenario : IFirstCutsceneScenario
Редуцируем интерфейс

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Tasks/TaskProcessQueue.cs
> +    public class TaskProcessQueue : ITaskProcessQueue
Используй имеющийся класс

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Tasks/TaskAwaiter.cs
> +    public class TaskAwaiter
Этот класс не нужен

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Tasks/ITaskProcessQueue.cs
> +    public interface ITaskProcessQueue
Редуируй этот интерфейс

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Scenario/FirstCutsceneScenario/FirstScenarioEvent.cs
> +    public class FirstScenarioEvent : IDisposable
Сделай вызов сценаиий из стартера, этот класс убери

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Scenario/FirstCutsceneScenario/IFirstCutsceneScenario.cs
> +    public interface IFirstCutsceneScenario : IScenario
Редуцируй интерфейс

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Cutscene/CutsceneInstaller.cs
> +    public class CutsceneInstaller : MonoInstaller
Переименуй в ScenarioInstaller

2024-10-12 08:48 UTC, ega-ega commented on Assets/Scripts/Gameplay/Cutscene/CutsceneInstaller.cs
> +        public override void InstallBindings()
Разбей по принципу клинкоду

2024-10-12 08:50 UTC, chexpk commented on Assets/Scripts/Gameplay/Cutscene/Cutscene.cs
> +        private void Construct(ICinemachineBrainProvider сinemachineBrainProvider)
done

2024-10-12 08:57 UTC, chexpk commented on Assets/Scripts/Gameplay/Scenario/FirstCutsceneScenario/FirstCutsceneScenario.cs
> +    public class FirstCutsceneScenario : IFirstCutsceneScenario
done

2024-10-12 08:57 UTC, chexpk commented on Assets/Scripts/Gameplay/Tasks/TaskProcessQueue.cs
> +    public class TaskProcessQueue : ITaskProcessQueue
done

2024-10-12 08:57 UTC, chexpk commented on Assets/Scripts/Gameplay/Tasks/TaskAwaiter.cs
> +    public class TaskAwaiter
done

2024-10-12 08:58 UTC, chexpk commented on Assets/Scripts/Gameplay/Tasks/ITaskProcessQueue.cs
> +    public interface ITaskProcessQueue
done

2024-10-12 08:58 UTC, chexpk commented on Assets/Scripts/Gameplay/Scenario/FirstCutsceneScenario/FirstScenarioEvent.cs
> +    public class FirstScenarioEvent : IDisposable
done

2024-10-12 08:58 UTC, chexpk commented on Assets/Scripts/Gameplay/Scenario/FirstCutsceneScenario/IFirstCutsceneScenario.cs
> +    public interface IFirstCutsceneScenario : IScenario
done

2024-10-12 10:11 UTC, chexpk commented on Assets/Scripts/Gameplay/Cutscene/CutsceneInstaller.cs
> +    public class CutsceneInstaller : MonoInstaller
done

2024-10-12 10:14 UTC, chexpk commented on Assets/Scripts/Gameplay/Cutscene/CutsceneInstaller.cs
> +        public override void InstallBindings()
done

2024-10-16 06:38 UTC, EgorShaldovRB requested changes

2024-10-16 06:38 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Camera/CameraProvider.cs
> +            //TODO need refactoring
убери комментарий

2024-10-16 06:38 UTC, EgorShaldovRB commented on Assets/Scripts/Gameplay/Camera/CameraProvider.cs
> +            if (MainCamera.gameObject.TryGetComponent(out CinemachineBrain cinemachineBrain))
переделай в 
       if (!MainCamera.gameObject.TryGetComponent(out _cinemachineBrain))
            {
            _cinemachineBrain = MainCamera.gameObject.AddComponent<CinemachineBrain>();
            }

2024-10-19 06:48 UTC, chexpk commented on Assets/Scripts/Gameplay/Camera/CameraProvider.cs
> +            //TODO need refactoring
done

2024-10-19 08:02 UTC, merged