Task completed: GP-117. Destroy by time
LighteatersStudio/TopDownShooter pull request #41
Opened 2023-05-16 16:58 UTC by Kjusok

https://lighteatersstudio.atlassian.net/jira/software/projects/GP/boards/1?selectedIssue=GP-117
Added Destroy projectile by time

2023-05-16 17:02 UTC, ega-ega requested changes

2023-05-16 17:02 UTC, ega-ega commented on Assets/Scripts/Gameplay/Projectile/Projectile.cs
> +        private const float TimeForDestroyShot = 5;
pls change to serialized field

2023-05-16 17:37 UTC, Kjusok commented on Assets/Scripts/Gameplay/Projectile/Projectile.cs
> +        private const float TimeForDestroyShot = 5;
Done

2023-05-16 18:52 UTC, ega-ega approved these changes

2023-05-17 07:53 UTC, ega-ega requested changes

2023-05-17 07:53 UTC, ega-ega commented on Assets/Scripts/Gameplay/Projectile/Projectile.cs
> +            var damageable = other.GetComponent<IDamageable>();
move this line under first if

2023-05-17 17:19 UTC, Kjusok commented on Assets/Scripts/Gameplay/Projectile/Projectile.cs
> +            var damageable = other.GetComponent<IDamageable>();
done

2023-05-17 17:30 UTC, ega-ega approved these changes

2023-05-17 17:31 UTC, merged