[WIP] GP-124. Added ammo clip and reload functionality
LighteatersStudio/TopDownShooter pull request #59
Opened 2023-05-30 22:29 UTC by frnzee

- added and implemented ammo clip class
- fixed input actions map for reloading
- added primitive game object for reload indicator

Need to move reload from ICanFire interface to a separate one, to add timer for reloading and some real indicator for that above the character.

2023-06-01 05:17 UTC, ega-ega requested changes

2023-06-01 05:17 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        public bool Shot()
Renam to waste bullet

2023-06-01 05:17 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +    public class AmmoClip : IWeapon
AmmoClip dont need implemnted IWeapon

2023-06-01 05:17 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        private int _bulletAmount;
rename to _amount

2023-06-01 05:17 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        private int _maxBulletAmount;
rename to _size

2023-06-03 06:36 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        public bool Shot()
done

2023-06-03 06:36 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +    public class AmmoClip : IWeapon
done

2023-06-03 06:36 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        private int _bulletAmount;
done

2023-06-03 06:36 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        private int _maxBulletAmount;
done

2023-06-03 07:39 UTC, ega-ega approved these changes

2023-06-03 07:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        public bool HasAmmo()
change to property

2023-06-03 07:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Character/ICanReload.cs
> +        float ReloadTime { get; }
remove from the interface

2023-06-03 07:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Character/ICanReload.cs
> +        event Action ReloadChanged;
rename to Reloaded

2023-06-03 07:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/IWeapon.cs
> +        bool WasteBullet();
Rename to Shot() please restore

2023-06-03 07:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Character/Character.cs
> +        public float ReloadTime { get; }
Pls remove

2023-06-03 07:39 UTC, ega-ega commented on Assets/Scripts/Gameplay/Weapons/Weapon.cs
> +                Debug.Log("Need reload");
Pls Remove

2023-06-03 07:47 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/AmmoClip.cs
> +        public bool HasAmmo()
done

2023-06-03 07:48 UTC, frnzee commented on Assets/Scripts/Gameplay/Character/ICanReload.cs
> +        float ReloadTime { get; }
done

2023-06-03 07:48 UTC, frnzee commented on Assets/Scripts/Gameplay/Character/ICanReload.cs
> +        event Action ReloadChanged;
done

2023-06-03 07:48 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/IWeapon.cs
> +        bool WasteBullet();
done

2023-06-03 07:48 UTC, frnzee commented on Assets/Scripts/Gameplay/Character/Character.cs
> +        public float ReloadTime { get; }
done

2023-06-03 07:48 UTC, ega-ega approved these changes

2023-06-03 07:48 UTC, ega-ega approved these changes

2023-06-03 07:48 UTC, frnzee commented on Assets/Scripts/Gameplay/Weapons/Weapon.cs
> +                Debug.Log("Need reload");
done

2023-06-03 07:48 UTC, merged