Added HighStoneSelector
LighteatersStudio/TopDownShooter pull request #7
Opened 2023-04-01 13:19 UTC by Kjusok

- Added screen with two buttons

2023-04-01 14:51 UTC, ega-ega requested changes

2023-04-01 14:51 UTC, ega-ega commented on Assets/Prefabs/UI/HighStoneChooseMenu/HighStoneChooseMenu.prefab
Move this file to Prefabs/UI/Popups/ . And remove folder for this prefab

2023-04-01 14:51 UTC, ega-ega commented on Assets/Prefabs/UI/StartSplashScreen/StartSplashScreen.prefab
Move this file to Prefabs/UI/Popups/ . And remove folder for this prefab. Bulat already moved this file to Popup folder

2023-04-02 18:18 UTC, Kjusok commented on Assets/Prefabs/UI/StartSplashScreen/StartSplashScreen.prefab
Done

2023-04-02 18:18 UTC, Kjusok commented on Assets/Prefabs/UI/HighStoneChooseMenu/HighStoneChooseMenu.prefab
Done

2023-04-02 18:18 UTC, ega-ega approved these changes

2023-04-02 18:18 UTC, merged