Task completed: GP-97 Collectable Weapon
LighteatersStudio/TopDownShooter pull request #86
Opened 2023-07-30 18:54 UTC by Kjusok

https://lighteatersstudio.atlassian.net/jira/software/projects/GP/boards/1?selectedIssue=GP-97

Added:
Abstract factory, pickup weapon prefabs, WeaponInitiatorDebug removed

2023-08-01 18:18 UTC, frnzee approved these changes

2023-08-09 19:14 UTC, frnzee approved these changes

2023-08-10 05:11 UTC, ega-ega requested changes

2023-08-10 05:11 UTC, ega-ega commented on Assets/Scripts/Gameplay/CollectableItems/WeaponCollectable.cs
> +        public void Construct(IPlayer player, Vector3 newPosition)
IPlayer ну нежно инжектить ты получаешь его при колизии. Убери этот инжект

2023-08-10 05:11 UTC, ega-ega commented on Assets/Scripts/Gameplay/CollectableItems/WeaponCollectable.cs
> +    public class WeaponCollectable : MonoBehaviour
Этот класс должен на старте смотреть в настройки и инстанцировать нужный префаб визуальный

2023-08-11 16:58 UTC, Kjusok commented on Assets/Scripts/Gameplay/CollectableItems/WeaponCollectable.cs
> +        public void Construct(IPlayer player, Vector3 newPosition)
Done

2023-08-12 07:40 UTC, Kjusok commented on Assets/Scripts/Gameplay/CollectableItems/WeaponCollectable.cs
> +    public class WeaponCollectable : MonoBehaviour
Done

2023-08-12 17:08 UTC, ega-ega approved these changes

2023-08-12 17:08 UTC, merged